services:
  db:
    image: mysql:8
    container_name: illegal-construction-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: illegal-construction-detection-project
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    profiles:
      - full-stack
    build: ./server
    container_name: illegal-construction-api
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env.development
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:root@db:3306/illegal-construction-detection-project
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    depends_on:
      - db

volumes:
  mysql_data:
